# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

demikernel:
  local_ipv4_addr: XX.XX.XX.XX
  local_link_addr: "ff:ff:ff:ff:ff:ff"
raw_socket:
  linux_interface_name: "abcde"
  xdp_interface_index: 0
  xdp_cohost_mode: false
  xdp_always_poke_tx: false
  # If true, will send all packets out on the interface identified by xdp_vf_interface_index;
  # otherwise, or if xdp_vf_interface_index is not set, will send packets out on the interface
  # identified by xdp_interface_index.
  xdp_always_send_on_vf: false
  # Enable the following for XDP cohosting mode, or override in environment:
  # xdp_tcp_ports: [80, 443]
  # xdp_udp_ports: [53]
  # Enable the following to reserve private port ranges from the OS for outgoing connections.
  # xdp_reserved_port_count: 8000
  # xdp_reserved_port_protocol: tcp
  # Enable the following line if you have a VF interface
  # xdp_vf_interface_index: 0
  # The number of buffers to allocate for sending packets. Must be larger than the tx_ring_size.
  tx_buffer_count: 4096
  # The number of buffers to allocate for receiving packets for each RSS queue. Must be larger than
  # the rx_ring_size.
  rx_buffer_count: 4096
  # The number of entries in the TX producer/consumer rings; must be a power of 2.
  tx_ring_size: 128
  # The number of entries in each RX producer/consumer ring for each RSS queue; must be a power of 2.
  rx_ring_size: 128
dpdk:
  eal_init: ["", "-c", "0xff", "-n", "4", "-a", "WW:WW.W","--proc-type=auto"]
tcp_socket_options:
  keepalive:
    enabled: false
    time_millis: 0
    interval: 0
  linger:
    enabled: true
    time_seconds: 0
  nodelay: true
inetstack_config:
  mtu: 1500
  mss: 1500
  enable_jumbo_frames: false
  udp_checksum_offload: false
  tcp_checksum_offload: false
  arp_table:
    "ff:ff:ff:ff:ff:ff": "XX.XX.XX.XX"
    "ff:ff:ff:ff:ff:ff": "YY.YY.YY.YY"
  arp_request_retries: 5
  arp_request_timeout: 20
  arp_cache_ttl: 15

# vim: set tabstop=2 shiftwidth=2
