# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Build

on:
  workflow_call:
    inputs:
      libos:
        required: true
        type: string
    secrets:
      host:
        required: true
      port:
        required: true
      key:
        required: true
      username:
        required: true

env:
  GITHUB_REPOSITORY: $GITHUB_REPOSITORY

jobs:

  #=====================================================================================================================
  # Build Doc
  #=====================================================================================================================

  build-doc:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Compile
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        key: ${{ secrets.key }}
        port: ${{ secrets.port }}
        envs: GITHUB_REPOSITORY
        script: |
          cd $GITHUB_REPOSITORY
          make doc

  #=====================================================================================================================
  # Check Formatting
  #=====================================================================================================================

  check-fmt:
    name: Check Formatting
    needs: [build-doc]
    runs-on: ubuntu-latest
    steps:
    - name: Compile
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        key: ${{ secrets.key }}
        port: ${{ secrets.port }}
        envs: GITHUB_REPOSITORY
        script: |
          cd $GITHUB_REPOSITORY
          make check-fmt LIBOS=${{ inputs.libos }}

  #=====================================================================================================================
  # Build Debug
  #=====================================================================================================================

  build-debug:
    name: Compile Debug
    needs: [check-fmt]
    runs-on: ubuntu-latest
    steps:
    - name: Compile
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        key: ${{ secrets.key }}
        port: ${{ secrets.port }}
        envs: GITHUB_REPOSITORY
        script: |
          cd $GITHUB_REPOSITORY
          make all DEBUG=yes LIBOS=${{ inputs.libos }}

  #=====================================================================================================================
  # Build Release
  #=====================================================================================================================

  build-release:
    name: Compile Release
    needs: [build-debug]
    runs-on: ubuntu-latest
    steps:
    - name: Compile
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        key: ${{ secrets.key }}
        port: ${{ secrets.port }}
        envs: GITHUB_REPOSITORY
        script: |
          cd $GITHUB_REPOSITORY
          make all DEBUG=no LIBOS=${{ inputs.libos }}